apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment
spec:
  resources:
    inputs:
      - {type: image, name: image}
  params:
    - name: deployment
      description: The name of the deployment patch the image
      type: string
  steps:
    - name: patch
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - |-
          oc patch deployment $(inputs.params.deployment) --patch='{"spec":{"template":{"spec":{
            "containers":[{
              "name": "$(inputs.params.deployment)",
              "image":"$(inputs.resources.image.url)"
            }]
          }}}}'